remote_theme: just-the-docs/just-the-docs

title: 職務経歴書
description: 内藤翔太の職務経歴書

# 目次 (TOC) を右サイドに表示
toc:
  enabled: true
  heading_level: 3

# サイドバー（目次として使用）
nav_enabled: true

# 検索バーを非表示
search_enabled: false

mermaid:
  version: "10"
